### ISSUE TITLE
Indent-region doesn't unindent correctly

### ISSUE THREAD

**Issue by reactormonk** [yoshiki/yaml-mode#24]
The yaml file

```
backgroundOrder:
- 13
- 44
backgroundStates:
- 9
- 10
columnOrder:
- ICON
- DISTANCE
```

is converted to

```
  backgroundOrder:
    - 13
    - 44
    backgroundStates:
      - 9
      - 10
      columnOrder:
        - ICON
        - DISTANCE
```
