### ISSUE TITLE
colon broke syntax highlight

### ISSUE THREAD

**Issue by osv** [yoshiki/yaml-mode#38]
Look how nice markdown highlight below:

```yaml
foo: |
  line1
  line2: <-- ooops colon cause to be as object!
  line3 <- ok again
  line4
bar:
  dsdf: null
```

And yaml-mode :)

![screenshot](http://ibin.co/2Yy7zSybCIL8)
