### ISSUE TITLE
Lacks JSON Support

### ISSUE THREAD

**Issue by grahamc** [yoshiki/yaml-mode#69]
As of YAML 1.2, YAML is an official super of JSON (https://yaml.org/spec/1.2/spec.html), however yaml-mode formats JSON like:

```yaml
{
"language": "nix",
"nix": "2.1",
"matrix": {
  "include": [
  {
  "name": "cargo pedantry",
  "script": "nix-shell --run checkPhase --arg useNix1 false -A mozilla-rust-overlay"
  },
  {
  "name": "checkPhase",
  "script": "nix-shell --run checkPhase --arg useNix1 false"
  }
  ]
  }
}
```
