### ISSUE TITLE
Wrong font lock used when highlighting an element containing a string with punctuation inside

### ISSUE THREAD

**Issue by codrut-fc** [yoshiki/yaml-mode#82]
<img width="576" alt="Screen Shot 2020-09-01 at 14 32 03" src="https://user-images.githubusercontent.com/66792133/91857655-144fa180-ec60-11ea-997e-ba0030016caf.png">

This bug:
- ~happens after line 46 (for some reason).~
- triggers when dealing with an array, having a quoted string that contains numbers and a colon punctuation.
- "fixes" itself temporarily by deleting the last quote, saving, undoing, then saving again; reappears when reloading the file.
- the highlighting of the rest of the file underneath is messed up by it.

This is especially troublesome with `docker-compose.yml` file where you define port mappings like:
```yml
services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
```

I have no idea how to investigate/fix this myself, so I'm asking for help (please) 🙏 !

EDIT: see https://github.com/yoshiki/yaml-mode/issues/82#issuecomment-758778827 below for an investigation done by @sulami.

**Comment by eeshugerman** [comment]
Glad it's not just me, I run into this a lot. I don't think line 46 is special in general, just in your example. Here's the simplest case I've managed to find:
```yaml
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: 'a.a'
a: 'a'

```
![image](https://user-images.githubusercontent.com/25518211/93029750-d2691880-f5da-11ea-8b0c-f62bda3fcba9.png)

(issue is present on the last line)
