### ISSUE TITLE
Sequence no-indent

### ISSUE THREAD

**Issue by holowinski** [yoshiki/yaml-mode#97]
Hi.

Is it possible to configure this mode to skip indentation for sequences?

A lot of kubernetes tooling prefers to format YAML with sequences not indented at all.
i.e. https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

uses

```
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
When using yaml-mode with editorconfig plugin every time `yaml-indent-offset` is called, sequences get indented which makes it unusable for the workflow with k8s files.
